### ISSUE TITLE
Better fix for #188 (not dropping trigger)

### ISSUE THREAD

**Issue by lekrus** [tomasfabian/Joker#13]
Hello Tomas,

In your "temp fix" to https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/issues/188
I see the only difference was to disable dropping all objects when there are no conversation handlers anymore, as that was causing a deadlock, e.g. you removed the below clauses:
```sql
DECLARE @conversationHandlerExists INT
SELECT @conversationHandlerExists = COUNT(*) FROM sys.conversation_endpoints WHERE conversation_handle = '{19}';
IF @conversationHandlerExists = 0
BEGIN
    {20}
    RETURN
END
```
the fix works great, but for cases when there is a transaction that goes beyond watch dog timeout, users still receive a blocking exception "The conversion handle XXX is not found", like here https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/issues/214

What do you think about returning back the clauses above with a single change:
```sql
DECLARE @conversationHandlerExists INT
SELECT @conversationHandlerExists = COUNT(*) FROM sys.conversation_endpoints WHERE conversation_handle = '{19}';
IF @conversationHandlerExists = 0
BEGIN
    -- doing nothing, just quit
    RETURN
END
```
e.g. for cases when we have some dropped conversation handlers but triggers are still staying in DB for some reason (or they appear to be present in DB in the scope of that running long-term transaction), we just silently skip any logic for that trigger.
As a result, users are not blocked from doing updates to the table?

Thanks!

**Comment by tomasfabian** [comment]
Hi @Lekrus,
your proposal sounds reasonable. Are you able to reproduce this issue and test it, in case that I release (you) a preview package with the above mentioned fix?

PS: this fix will be hopefully permanent not temp this time ;)

**Comment by lekrus** [comment]
Hi Tomas,

Thanks for the prompt reply!
Unfortunately, after trying multiple ways to simulate the error I failed.
But we do see that situation for one of our test servers. The situation is always similar - there is tr_XXX trigger that is not yet removed and then all updates fail, in some time - the error is self-resolved as tr_XXX trigger is removed.
Let's close this ticket for now, when/if I have more evidence - I'll reopen it.

Thank you for your time!
