### ISSUE TITLE
VARCHAR(MAX) creates an error when Trigger is generated

### ISSUE THREAD

**Issue by ronnysolheim** [tomasfabian/Joker#29]
A VARCHAR(MAX) becomes like:
 DECLARE @modifiedRecordsTable TABLE ([RowNumber] INT IDENTITY(1, 1), [Note] VARCHAR(-1) ....

**Comment by tomasfabian** [comment]
Hello @ronnysolheim, the issue should be moved to this repository: https://github.com/IsNemoEqualTrue/monitor-table-change-with-sqltabledependency. Thanks.
