### ISSUE TITLE
Maintain conversation

### ISSUE THREAD

**Issue by mbowles201** [tomasfabian/Joker#9]
Not an issue, per se.
We are using SqlTableDependency have an issue with the drop and recreate of triggers and broker items each time it "hiccups"  A windows service makes use of the project to listen to the broker.   If our service idels or drops and has to be restarted, the drop and create from SqlTableDependecny fires...during that time, the db is nearly unusable.  Your extension mentions the ability to maintain that conversation handle.  Would your extension help us in those situations?

**Comment by tomasfabian** [comment]
Hi @mbowles201 the best way how to find this out is to try it in your environment. My extension tries to reestablish the same conversation handle as before within a specified period. This period can be set, but be aware that the message queue will grow during this period, in case that the messages won't be consumed by your service. These messages could overwhelm your service after reconnection, so please try this out, too.

I hope this will be somehow helpful to you. Let us know how did you manage your issue.
Thank you, Tomas

**Comment by mbowles201** [comment]
Thanks! I will give that a whirl as soon as I go through the "how to" section.  Really dont want to alter anything except to add the "reconnect" capability.
Thanks again.

**Comment by tomasfabian** [comment]
This package extends SqlTableDependency.

**Comment by tomasfabian** [comment]
Closed due to inactivity
